const Log = require("./logger");

const ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJzbmVoaXRyYW1rdW1hci55MjAyMkB2aXRzdHVkZW50LmFjLmluIiwiZXhwIjoxNzc4OTI5MTAzLCJpYXQiOjE3Nzg5MjgyMDMsImlzcyI6IkFmZm9yZCBNZWRpY2FsIFRlY2hub2xvZ2llcyBQcml2YXRlIExpbWl0ZWQiLCJqdGkiOiI4NWU1MDZjNS1kYjdlLTQ2YjAtOTc3Yi1lMmNlYTQxNzQzYTQiLCJsb2NhbGUiOiJlbi1JTiIsIm5hbWUiOiJzbmVoaXQgcmFtIGt1bWFyIiwic3ViIjoiZjVjYzE5ODAtMDA3OC00MmQ5LTg5OTQtNWU4N2JjNWRmZjRkIn0sImVtYWlsIjoic25laGl0cmFta3VtYXIueTIwMjJAdml0c3R1ZGVudC5hYy5pbiIsIm5hbWUiOiJzbmVoaXQgcmFtIGt1bWFyIiwicm9sbE5vIjoiMjJtaXMxMTY5IiwiYWNjZXNzQ29kZSI6IlNmRnVXZyIsImNsaWVudElEIjoiZjVjYzE5ODAtMDA3OC00MmQ5LTg5OTQtNWU4N2JjNWRmZjRkIiwiY2xpZW50U2VjcmV0IjoiR3dQdWNtQnVlUHBta2tCeSJ9.tF4li1bREkU0iCSasuArftnut26zOAFtNHjhsOCmGB8";

// Example log calls
Log("backend", "error", "handler", "Invalid input received", ACCESS_TOKEN);
Log("backend", "fatal", "db", "Database connection failed", ACCESS_TOKEN);
module.exports = Log;